name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "@memdborg/reviewers"
        include-draft: false
